WebSiteBanHang/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;
using System.Net.Mail; // send mail

namespace WebSiteBanHang.Controllers
{
  [Authorize(Roles = "10")]
  public class QuanLyDonHangController : Controller
  {
    //
    // GET: /QuanLyDonHang/
    QuanLyBanHangEntities db = new QuanLyBanHangEntities();
    
    public ActionResult ChoDuyet()
    {
      var lst = db.DONDATHANGs.Where(n => n.TinhTrangGiaoHang == -1).OrderBy(p => p.ThoiDiemDat);
      return View(lst);
    }
    [HttpGet]
    public ActionResult DuyetDonHang(int? id)
    {
      //Kiểm tra xem id hợp lệ không
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      DONDATHANG model = db.DONDATHANGs.SingleOrDefault(n => n.MaDDH == id);
      NGUOIDUNG khachHang = db.NGUOIDUNGs.Single(n => n.MaNguoiDung == model.MaKH);
      //Kiểm tra đơn hàng có tồn tại không
      if (model == null)
      {
        return HttpNotFound();
      }
      //Lấy danh sách chi tiết đơn hàng để hiển thị cho người dùng thấy
      var lstChiTietDH = db.CHITIETDONDATHANGs.Where(n => n.MaDDH == id);
      ViewBag.ListChiTietDH = lstChiTietDH;
      ViewBag.TenKH = khachHang.Ho+" "+khachHang.TenLot+ " " + khachHang.Ten;
      return View(model);
    }
    public ActionResult DaDuyet()
    {
      var lst = db.DONDATHANGs.Where(n => n.TinhTrangGiaoHang == 0).OrderBy(p => p.ThoiDiemLap);
      return View(lst);
    }
    public ActionResult DaTuChoi()
    {
      var lst = db.DONDATHANGs.Where(n => n.TinhTrangGiaoHang == 1).OrderBy(p => p.ThoiDiemDat);
      return View(lst);
    }
    [HttpPost]
    public ActionResult DuyetDonHang(DONDATHANG ddh)
    {
      //Truy vấn lấy ra dữ liệu của đơn hàn đó 
      DONDATHANG ddhUpdate = db.DONDATHANGs.Single(n => n.MaDDH == ddh.MaDDH);
      //ddhUpdate.DaThanhToan = ddh.DaThanhToan;
      ddhUpdate.TinhTrangGiaoHang = 0;
      ddhUpdate.MaNV = (Session["NGUOIDUNG"] as NGUOIDUNG).MaNguoiDung;
      ddhUpdate.ThoiDiemLap = DateTime.Now;
      ddhUpdate.NgayGiaoDuKien = ddh.NgayGiaoDuKien;
      db.SaveChanges();
      //Lấy danh sách chi tiết đơn hàng để hiển thị cho người dùng thấy
      var lstChiTietDH = db.CHITIETDONDATHANGs.Where(n => n.MaDDH == ddh.MaDDH);
      //Cập nhật số lượng tồn của từng sản phẩm
      foreach(var item in lstChiTietDH)
      {
        SANPHAM spUpdate = db.SANPHAMs.Single(n => n.MaSP == item.MaSP);
        spUpdate.SoLuongTon -= item.SoLuong;
      }
      ViewBag.ListChiTietDH = lstChiTietDH;
      //Gửi khách hàng 1 mail để xác nhận việc thanh toán 
      GuiEmail("Xác nhận đơn hàng từ xuancongduy.com", "hntxuanit15spkt@gmail.com", "nguyennhi.cave@gmail.com", "15110376", "Đơn hàng của bạn đã được đặt thành công!");
      return View(ddhUpdate);
    }
    public void GuiEmail(string Title, string ToEmail, string FromEmail, string PassWord, string Content)
    {
      // goi email
      MailMessage mail = new MailMessage();
      mail.To.Add(ToEmail); // Địa chỉ nhận
      mail.From = new MailAddress(ToEmail); // Địa chửi gửi
      mail.Subject = Title;  // tiêu đề gửi
      mail.Body = Content;                 // Nội dung
      mail.IsBodyHtml = true;
      SmtpClient smtp = new SmtpClient();
      smtp.Host = "smtp.gmail.com"; // host gửi của Gmail
      smtp.Port = 587;               //port của Gmail
      smtp.UseDefaultCredentials = false;
      smtp.Credentials = new System.Net.NetworkCredential
      (FromEmail, PassWord);//Tài khoản password người gửi
      smtp.EnableSsl = true;   //kích hoạt giao tiếp an toàn SSL
      smtp.Send(mail);   //Gửi mail đi
    }


    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        if (db != null)
          db.Dispose();
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

WebSiteBanHang/Views/QuanLyDonHang/ChoDuyet.cshtml
@using WebSiteBanHang.Models
@model IEnumerable<DONDATHANG>


@{
  ViewBag.Title = "ChoDuyet";
  Layout = "~/Views/Layout/AdminLayout.cshtml";
  WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng</h2>
<ul class="nav nav-tabs">
  <li role="presentation" class="active">
    <a href="@Url.Action("ChoDuyet","QuanLyDonHang")">Chờ duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaDuyet","QuanLyDonHang")">Đã duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaTuChoi","QuanLyDonHang")">Đã từ chối</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaGiao","QuanLyDonHang")">Đã giao</a>
  </li>
</ul>
<br />
@grid.GetHtml(
  tableStyle: "divTable",
  headerStyle: "gridHead",
  footerStyle: "gridRow",
  alternatingRowStyle: "gridAltRow",
  columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"),
    grid.Column("ThoiDiemDat", header: "Thời điểm đặt hàng"),
    grid.Column("UuDai", header: "Ưu đãi"),
    grid.Column("TongTien", header: "Tổng tiền đơn hàng"),
    grid.Column("PhiVanChuyen", header: "Phí vận chuyển"),
    grid.Column("DiaChiNhanHang", header: "Địa chỉ nhận hàng"),
    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { @id = p.MaDDH }, new { @target = "_blank" }))
    )
)
<style>
  .nav > li {
    background: rgba(0,0,0,.5);
  }

  .divTable {
    width: 100%;
    border: 1px solid #999999;
  }

    .divTable td {
      border: 1px solid #999999;
    }

  .gridHead {
    background-color: Green;
  }

    .gridHead > th > a {
      color: #fff;
    }

  .gridFooter {
    font-weight: bold;
  }

  .divTable a {
    color: blue;
  }
</style>

WebSiteBanHang/Views/QuanLyDonHang/ChuaGiao.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "ChuaGiao";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}
<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa giao đã thanh toán)</h2>  <br />
@*Dùng boostrap tạo 1 tab control với các liên kết đến các view khác*@
<ul class="nav nav-tabs">
    <li role="presentation" ><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>

<br /><br />

@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH",header: "Mã đơn hàng"),
            grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),  //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        grid.Column("DaHuy", header: "Đã hủy"),
    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

        ))

<style>
    .nav>li {
        background: rgba(0,0,0,.5);
        
    }
   .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

    .divTable td {
        border: 1px solid #999999;
    }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    .divTable  a {
        color:blue;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/

   
</style>

WebSiteBanHang/Views/QuanLyDonHang/ChuaThanhToan.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}


<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa thanh toán)</h2>
<br />
@*Tab quản lý các trạng thái của đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>       <br />
@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"),
        grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""), //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        grid.Column("DaHuy", header: "Đã hủy"),
    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

        ))

@*Css cho controller*@
<style>
    .nav > li {
        background: rgba(0,0,0,.5);
    }

    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/
</style>

WebSiteBanHang/Views/QuanLyDonHang/DaDuyet.cshtml
@model IEnumerable<WebSiteBanHang.Models.DONDATHANG>


@{
  ViewBag.Title = "DaDuyet";
  Layout = "~/Views/Layout/AdminLayout.cshtml";
  WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}
<ul class="nav nav-tabs">
  <li role="presentation">
    <a href="@Url.Action("ChoDuyet","QuanLyDonHang")">Chờ duyệt</a>
  </li>
  <li role="presentation" class="active">
    <a href="@Url.Action("DaDuyet", "QuanLyDonHang")">Đã duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaTuChoi","QuanLyDonHang")">Đã từ chối</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaGiao","QuanLyDonHang")">Đã giao</a>
  </li>
</ul>
<br/>
@grid.GetHtml(
  tableStyle: "divTable",
  headerStyle: "gridHead",
  footerStyle: "gridRow",
  alternatingRowStyle: "gridAltRow",
  columns: grid.Columns(
    grid.Column("MaDDH", "Mã đơn"),
    grid.Column("ThoiDiemDat", header: "Thời điểm đặt"),
    grid.Column("ThoiDiemLap", header: "Thời điểm lập hóa đơn"),
    grid.Column("NgayGiaoDuKien", header: "Ngày giao"),
    grid.Column("UuDai", header: "Ưu đãi"),
    grid.Column("TongTien", header: "Tổng tiền"),
    grid.Column("PhiVanChuyen", header: "Phí vận chuyển"),
    grid.Column("DiaChiNhanHang", header: "Địa chỉ nhận hàng")
    )
)
<style>
  .nav > li {
    background: rgba(0,0,0,.5);
  }

  .divTable {
    width: 100%;
    border: 1px solid #999999;
  }

    .divTable td {
      border: 1px solid #999999;
    }

  .gridHead {
    background-color: Green;
  }

    .gridHead > th > a {
      color: #fff;
    }

  .gridFooter {
    font-weight: bold;
  }

  .divTable a {
    color: blue;
  }
</style>

WebSiteBanHang/Views/QuanLyDonHang/DaGiao.cshtml
@model IEnumerable<WebSiteBanHang.Models.DONDATHANG>


@{
  ViewBag.Title = "DaGiao";
  Layout = "~/Views/Layout/AdminLayout.cshtml";
  WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}
<ul class="nav nav-tabs">
  <li role="presentation">
    <a href="@Url.Action("ChoDuyet","QuanLyDonHang")">Chờ duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaDuyet", "QuanLyDonHang")">Đã duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaTuChoi","QuanLyDonHang")">Đã từ chối</a>
  </li>
  <li role="presentation" class="active">
    <a href="@Url.Action("DaGiao","QuanLyDonHang")">Đã giao</a>
  </li>
</ul>
<br />
@grid.GetHtml(
  tableStyle: "divTable",
  headerStyle: "gridHead",
  footerStyle: "gridRow",
  alternatingRowStyle: "gridAltRow",
  columns: grid.Columns(
    grid.Column("MaDDH", "Mã đơn hàng"),
    grid.Column("ThoiDiemDat", header: "Thời điểm đặt"),
    grid.Column("ThoiDiemLap", header: "Thời điểm lập hóa đơn"),
    grid.Column("UuDai", header: "Ưu đãi"),
    grid.Column("NgayGiaoDuKien", header: "Ngày giao"),
    grid.Column("TongTien", header: "Tổng tiền"),
    grid.Column("PhiVanChuyen", header: "Phí vận chuyển"),
    grid.Column("DiaChiNhanHang", header: "Địa chỉ nhận hàng")
    )
)
<style>
  .nav > li {
    background: rgba(0,0,0,.5);
  }

  .divTable {
    width: 100%;
    border: 1px solid #999999;
  }

    .divTable td {
      border: 1px solid #999999;
    }

  .gridHead {
    background-color: Green;
  }

    .gridHead > th > a {
      color: #fff;
    }

  .gridFooter {
    font-weight: bold;
  }

  .divTable a {
    color: blue;
  }
</style>

WebSiteBanHang/Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@model IEnumerable<WebSiteBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "DaGiaoDaThanhToan";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng đã giao và thanh toán)</h2>      <br />
@*Dùng boostrap tạo 1 tab control với các liên kết đến các view khác*@
<ul class="nav nav-tabs">
    <li role="presentation"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" ><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán </a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>
<br />
@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được 
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"),
            grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""), //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        grid.Column("DaHuy", header: "Đã hủy"),
    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" }))

        ))

<style>
    .nav > li {
        background: rgba(0,0,0,.5);
    }

    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/
</style>

WebSiteBanHang/Views/QuanLyDonHang/DaTuChoi.cshtml
@model IEnumerable<WebSiteBanHang.Models.DONDATHANG>


@{
  ViewBag.Title = "DaTuChoi";
  Layout = "~/Views/Layout/AdminLayout.cshtml";
  WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}
<ul class="nav nav-tabs">
  <li role="presentation">
    <a href="@Url.Action("ChoDuyet","QuanLyDonHang")">Chờ duyệt</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaDuyet", "QuanLyDonHang")">Đã duyệt</a>
  </li>
  <li role="presentation" class="active">
    <a href="@Url.Action("DaTuChoi","QuanLyDonHang")">Đã từ chối</a>
  </li>
  <li role="presentation">
    <a href="@Url.Action("DaGiao","QuanLyDonHang")">Đã giao</a>
  </li>
</ul>
<br />
@grid.GetHtml(
  tableStyle: "divTable",
  headerStyle: "gridHead",
  footerStyle: "gridRow",
  alternatingRowStyle: "gridAltRow",
  columns: grid.Columns(
    grid.Column("MaDDH", "Mã đơn đặt hàng"),
    grid.Column("ThoiDiemDat", header: "Thời điểm đặt hàng"),
    grid.Column("ThoiDiemLap", header: "Thời điểm lập hóa đơn"),
    grid.Column("UuDai", header: "Ưu đãi"),
    grid.Column("TongTien", header: "Tổng tiền đơn hàng"),
    grid.Column("PhiVanChuyen", header: "Phí vận chuyển"),
    grid.Column("DiaChiNhanHang", header: "Địa chỉ nhận hàng")
    )
)
<style>
  .nav > li {
    background: rgba(0,0,0,.5);
  }

  .divTable {
    width: 100%;
    border: 1px solid #999999;
  }

    .divTable td {
      border: 1px solid #999999;
    }

  .gridHead {
    background-color: Green;
  }

    .gridHead > th > a {
      color: #fff;
    }

  .gridFooter {
    font-weight: bold;
  }

  .divTable a {
    color: blue;
  }
</style>

WebSiteBanHang/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WebSiteBanHang.Models;
@model DONDATHANG

  @{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
  }

  @*<h2>Thông tin đơn hàng <font color="#f65e84">@Model.KhachHang.TenKH</font></h2>*@
<h2>Thông tin đơn hàng của khách hàng <font color="#f65e84">@ViewBag.TenKH</font></h2>
  <br /><br />

  @using (Html.BeginForm())
  {
    <div class="ChiTietDonHang table">
      @{IEnumerable<CHITIETDONDATHANG> lstChiTietDH = (IEnumerable<CHITIETDONDATHANG>)ViewBag.ListChiTietDH;}
      <table class="table" id="table">
        @*Phần thông tin đơn hàng*@
        <tr>
          <td colspan="4">
            <table style="width:100%;">
              <tr>
                <td>Mã đơn hàng: <b style="color:red;"> @Model.MaDDH @Html.Hidden("MaDDH", @Model.MaDDH)</b></td>
                <td>Tên khách hàng: <b style="color:red;"> @ViewBag.TenKH</b></td>
                <td>Thời điểm đặt: @Model.ThoiDiemDat.Value.ToString("dd/MM/yyyy")</td>
                <td>Ngày giao: <input type="date" name="NgayGiaoDuKien"/></td>
                @*<td>Đã thanh toán: @Html.EditorFor(model => model.DaThanhToan)</td>
                <td>Đã giao: @Html.EditorFor(model => model.TinhTrangGiaoHang)</td>*@
              </tr>
            </table>

          </td>
        </tr>



        @*Thông tin chi tiết đơn hàng*@


        <tr>
          <td><b>Sản phẩm</b></td>
          <td><b>Hình ảnh</b></td>
          <td><b>Số lượng đặt</b></td>
          <td><b>Đơn giá</b></td>
        </tr>

        @foreach (var item in lstChiTietDH)
        {
          <tr>
            <td>@item.SANPHAM.TenSP</td>
            <td><img width="200" height="100" src="@Url.Content("~/Content/HinhAnhSP/"+item.SANPHAM.HinhAnh)" /></td>
            <td>@item.SoLuong</td>
            <td>@item.SANPHAM.DonGia</td>
        </tr>
        }
        <tr>
          <td align="right" colspan="4">Tổng số lượng: @Model.CHITIETDONDATHANGs.Sum(n => n.SoLuong) sản phẩm</td>
        </tr>
        <tr>
          <td align="right" colspan="4">Tổng tiền: @Model.TongTien.Value.ToString("#,##") đồng</td>
        </tr>
      </table>
      <br /><br />
      <input type="button" value="In đơn hàng" id="btnInDonHang" />
      <input type="submit" value="Lưu đơn hàng" id="btnInDonHang" />
    </div>
        }

  <script>

    $("#btnInDonHang").click(function () {
      var content = "<table>" + $("#table").html() + "</table>";
      InDonHang(content);
    });

    //Phương thức in
    function InDonHang(content) {
      var printWindow = window.open('', '', 'height=400,width=800');
      printWindow.document.write('<html><head><title>DIV Contents</title>');
      printWindow.document.write('</head><body >');
      printWindow.document.write(content);
      printWindow.document.write('</body></html>');
      printWindow.document.close();
      printWindow.print();
    }

  </script>